name: snacker
description: A top-level snack bar presenter.

publish_to: none

environment:
  sdk: ^3.10.9

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
