builders:
  json_parser_builder:
    import: "package:parser_generator/src/builders/json_parser/builders/json_parser_builder.dart"
    builder_factories: [ "jsonParserBuilder" ]
    build_extensions: { ".dart": [ ".g.dart" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]
    defaults:
      options:
        always_generate: true
        config_file: parser_config.yaml