name: app_analyzer_plugin_loader
description: Bootstrap for the enclosing analyzer plugin package.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.5.0

# Add regular dependencies here
dependencies:
  # Put the enclosing analyzer plugin package dependency.
  # Be sure to change this to a pub/git based dependency before merging.
  # For local testing, if using (file) path based dependency, ensure you are putting absolute path.
  app_analyzer:
    path: /Users/ragib/AndroidStudioProjects/dart-flutter-packages/app_analyzer

dev_dependencies:
  test: ^1.25.5

  # Lints
  lints: ^3.0.0
  very_good_analysis: ^5.1.0
