import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/dart/element/element2.dart';
import 'package:analyzer_core/src/models/parameter_signature.dart';
import 'package:equatable/equatable.dart';

/// Represents the signature of a Dart class constructor.
///
/// This class encapsulates all metadata and parameters about a constructor,
/// making it easier to analyze and manipulate constructor information
/// outside of the analyzer's AST structure.
class ConstructorSignature extends Equatable {
  /// Whether this constructor is declared with the `const` keyword.
  ///
  /// Const constructors can be used to create compile-time constant objects.
  final bool isConst;

  /// Whether this constructor is static.
  ///
  /// Note: Constructors in Dart aren't typically declared as static,
  /// but factory constructors behave somewhat like static methods.
  final bool isStatic;

  /// Whether this constructor is public (accessible outside its library).
  ///
  /// A constructor is public when its name doesn't start with an underscore.
  final bool isPublic;

  /// Whether this constructor is private (only accessible within its library).
  ///
  /// A constructor is private when its name starts with an underscore.
  final bool isPrivate;

  /// Whether this constructor is declared with the `factory` keyword.
  ///
  /// Factory constructors don't always create a new instance of their class
  /// and can return instances of subclasses or existing instances.
  final bool isFactory;

  /// Whether this constructor is declared with the `external` keyword.
  ///
  /// External constructors have their implementation provided externally.
  final bool isExternal;

  /// Whether this constructor is synthetic (not explicitly declared in code).
  ///
  /// Synthetic constructors are generated by the compiler, such as the
  /// default constructor when none is explicitly provided.
  final bool isSynthetic;

  /// The name of the constructor.
  ///
  /// - For default constructors, this will be an empty string.
  /// - For named constructors, this will be the name after the dot
  /// (e.g., "named" in "Class.named").
  final String name;

  /// The list of parameters this constructor accepts.
  ///
  /// Each parameter is represented by a [ParameterSignature] object.
  final List<ParameterSignature> parameters;

  /// Creates a new [ConstructorSignature] with the specified properties.
  const ConstructorSignature({
    required this.isConst,
    required this.isStatic,
    required this.isPublic,
    required this.isPrivate,
    required this.isFactory,
    required this.isExternal,
    required this.isSynthetic,
    required this.name,
    required this.parameters,
  });

  /// Creates a [ConstructorSignature] from a [ConstructorElement] instance.
  ///
  /// This factory constructor extracts all relevant information from
  /// the AST node and constructs a new [ConstructorSignature] instance.
  ///
  /// If any information is not available in the AST node
  /// (e.g., if elements are null), sensible defaults are used.
  factory ConstructorSignature.fromConstructorElement(
    ConstructorElement element,
  ) {
    return ConstructorSignature(
      isConst: element.isConst,
      isStatic: element.isStatic,
      isPublic: element.isPublic,
      isPrivate: element.isPrivate,
      isFactory: element.isFactory,
      isExternal: element.isExternal,
      isSynthetic: element.isSynthetic,
      // Per doc, The `name` may be null, but it is non-nullable.
      // Using this redundant null check to avoid any runtime crashes.
      // ignore: dead_null_aware_expression
      name: element.name ?? '',
      parameters: element.parameters
          .map(
            (p) => ParameterSignature(
              type: p.type,
              // Per doc, The `name` may be null, but it is non-nullable.
              // Using this redundant null check to avoid any runtime crashes.
              // ignore: dead_null_aware_expression
              name: p.name ?? '',
              isNamed: p.isNamed,
              isRequired: p.isRequired,
            ),
          )
          .toList(),
    );
  }

  /// Creates a [ConstructorSignature] from a [ConstructorElement2] instance.
  ///
  /// This factory constructor extracts all relevant information from
  /// the AST node and constructs a new [ConstructorSignature] instance.
  ///
  /// If any information is not available in the AST node
  /// (e.g., if elements are null), sensible defaults are used.
  factory ConstructorSignature.fromConstructorElement2(
    ConstructorElement2 element,
  ) {
    return ConstructorSignature(
      isConst: element.isConst,
      isStatic: element.isStatic,
      isPublic: element.isPublic,
      isPrivate: element.isPrivate,
      isFactory: element.isFactory,
      isExternal: element.isExternal,
      isSynthetic: element.isSynthetic,
      name: element.name3 ?? '',
      parameters: element.formalParameters
          .map(
            (p) => ParameterSignature(
              type: p.type,
              name: p.name3 ?? '',
              isNamed: p.isNamed,
              isRequired: p.isRequired,
            ),
          )
          .toList(),
    );
  }

  @override
  List<Object> get props => [
        isConst,
        isStatic,
        isPublic,
        isPrivate,
        isFactory,
        isExternal,
        isSynthetic,
        name,
        parameters,
      ];
}
