import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/dart/element/element2.dart';
import 'package:analyzer/dart/element/type.dart';
import 'package:analyzer_core/src/models/parameter_signature.dart';
import 'package:equatable/equatable.dart';

/// Represents the signature of a Dart class method.
///
/// This class encapsulates all metadata and parameters about a method,
/// including its modifiers, return type, and parameters. It provides a
/// simplified view of method information extracted from the analyzer's
/// AST structure.
class MethodSignature extends Equatable {
  /// Whether this method is declared with the `static` keyword.
  ///
  /// Static methods belong to the class itself rather than to instances
  /// of the class.
  final bool isStatic;

  /// Whether this method is public (accessible outside its library).
  ///
  /// A method is public when its name doesn't start with an underscore.
  final bool isPublic;

  /// Whether this method is private (only accessible within its library).
  ///
  /// A method is private when its name starts with an underscore.
  final bool isPrivate;

  /// Whether this method is declared with the `external` keyword.
  ///
  /// External methods have their implementation provided externally.
  final bool isExternal;

  /// Whether this method is declared with the `abstract` keyword.
  ///
  /// Abstract methods don't have an implementation in the class where
  /// they're declared and must be implemented by non-abstract subclasses.
  final bool isAbstract;

  /// Whether this method is synthetic (not explicitly declared in code).
  ///
  /// Synthetic methods are generated by the compiler, such as implicit
  /// getters and setters for properties.
  final bool isSynthetic;

  /// The name of the method.
  final String name;

  /// The return type of the method.
  ///
  /// Can be null if the return type is not explicitly specified
  /// or couldn't be resolved.
  final DartType? returnType;

  /// The list of parameters this method accepts.
  ///
  /// Each parameter is represented by a [ParameterSignature] object.
  final List<ParameterSignature> parameters;

  /// Creates a new [MethodSignature] with the specified properties.
  ///
  /// All parameters are required to ensure complete method signature
  /// information.
  const MethodSignature({
    required this.isStatic,
    required this.isPublic,
    required this.isPrivate,
    required this.isExternal,
    required this.isAbstract,
    required this.isSynthetic,
    required this.name,
    required this.returnType,
    required this.parameters,
  });

  /// Creates a [MethodSignature] from a [ExecutableElement] instance.
  ///
  /// This factory constructor extracts all relevant information
  /// from the AST node and constructs a new [MethodSignature] instance.
  ///
  /// If any information is not available in the AST node
  /// (e.g., if elements are null), sensible defaults are used.
  factory MethodSignature.fromMethodElement(ExecutableElement element) {
    return MethodSignature(
      isStatic: element.isStatic,
      isPublic: element.isPublic,
      isPrivate: element.isPrivate,
      isExternal: element.isExternal,
      isAbstract: element.isAbstract,
      isSynthetic: element.isSynthetic,
      // Per doc, The `name` may be null, but it is non-nullable.
      // Using this redundant null check to avoid any runtime crashes.
      // ignore: dead_null_aware_expression
      name: element.name ?? '',
      returnType: element.returnType,
      parameters: element.parameters
          .map(
            (p) => ParameterSignature(
              type: p.type,
              // Per doc, The `name` may be null, but it is non-nullable.
              // Using this redundant null check to avoid any runtime crashes.
              // ignore: dead_null_aware_expression
              name: p.name ?? '',
              isNamed: p.isNamed,
              isRequired: p.isRequired,
            ),
          )
          .toList(),
    );
  }

  /// Creates a [MethodSignature] from a [ExecutableElement2] instance.
  ///
  /// This factory constructor extracts all relevant information
  /// from the AST node and constructs a new [MethodSignature] instance.
  ///
  /// If any information is not available in the AST node
  /// (e.g., if elements are null), sensible defaults are used.
  factory MethodSignature.fromMethodElement2(ExecutableElement2 element) {
    return MethodSignature(
      isStatic: element.isStatic,
      isPublic: element.isPublic,
      isPrivate: element.isPrivate,
      isExternal: element.isExternal,
      isAbstract: element.isAbstract,
      isSynthetic: element.isSynthetic,
      name: element.name3 ?? '',
      returnType: element.returnType,
      parameters: element.formalParameters
          .map(
            (p) => ParameterSignature(
              type: p.type,
              name: p.name3 ?? '',
              isNamed: p.isNamed,
              isRequired: p.isRequired,
            ),
          )
          .toList(),
    );
  }

  /// The list of properties used for equality comparisons and
  /// hash code generation.
  @override
  List<Object?> get props => [
        isStatic,
        isPublic,
        isPrivate,
        isExternal,
        isAbstract,
        isSynthetic,
        name,
        returnType,
        parameters,
      ];
}
