name: radio_group
description: A fully customizable radio group.

repository: https://github.com/Ragibn5/dart-flutter-packages
issue_tracker: https://github.com/Ragibn5/dart-flutter-packages/issues
homepage: https://github.com/Ragibn5/dart-flutter-packages/tree/main/radio_group

# This prevents you from accidentally publish to pub.dev
publish_to: 'none'

# Library version
version: 0.0.1

# Range of compatible SDK versions
environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

# Regular dependencies
# (Bundled in executable artifact)
dependencies:
  flutter:
    sdk: flutter
  mocktail: ^1.0.4

# Dev dependencies
# (NOT Bundled in executable artifact - For DEV use only)
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0