name: net_kit
description: An opinionated wrapper around dio that streamlines request/response transformation and error handling.

repository: https://github.com/Ragibn5/dart-flutter-packages
issue_tracker: https://github.com/Ragibn5/dart-flutter-packages/issues
homepage: https://github.com/Ragibn5/dart-flutter-packages/tree/main/net_kit

# This prevents you from accidentally publish to pub.dev
publish_to: 'none'

# Library version
version: 0.0.1

# Range of compatible SDK versions
environment:
  sdk: ^3.0.6

# Regular dependencies
# (Bundled in executable artifact)
dependencies:
  dio: ^5.8.0+1
  parser:
    path: ../parser
  functions:
    path: ../functions

# Dev dependencies
# (NOT Bundled in executable artifact - For DEV use only)
dev_dependencies:
  test: ^1.25.5
  mocktail: ^1.0.5
  lints: ^3.0.0
  very_good_analysis: ^5.1.0
