name: sqlite_db
description: SQLite database.

repository: https://github.com/Ragibn5/dart-flutter-packages
issue_tracker: https://github.com/Ragibn5/dart-flutter-packages/issues
homepage: https://github.com/Ragibn5/dart-flutter-packages/tree/main/sqlite_db

# Library version
version: 1.0.0

# Range of compatible SDK versions
environment:
  sdk: ^3.11.0

# Regular dependencies
dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  meta: ^1.12.0
  sqflite: ^2.4.2
  disposable:
    path: ../disposable
  initializable:
    path: ../initializable
  dart_functionals:
    path: ../dart_functionals

# Dev dependencies
# (NOT Bundled in executable artifact - For DEV use only)
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  lints: ^3.0.0
  very_good_analysis: ^5.1.0
