name: app_analyzer
description: A custom analyzer plugin for flutter apps.

repository: https://github.com/Ragibn5/dart-flutter-packages
issue_tracker: https://github.com/Ragibn5/dart-flutter-packages/issues
homepage: https://github.com/Ragibn5/dart-flutter-packages/tree/main/app_analyzer

# This prevents you from accidentally publish to pub.dev
publish_to: 'none'

# Library version
version: 0.0.1

# Range of compatible SDK versions
environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.7.0
  path: ^1.9.1
  analyzer: ^7.4.5
  analyzer_plugin: ^0.13.0

  analyzer_core:
    path: ../../dart-flutter-packages/analyzer_core

  # Add analyzers here
  parser_analyzer:
    path: ../../dart-flutter-packages/parser_analyzer

dev_dependencies:
  # Test
  test: ^1.25.5

  # Lints
  lints: ^5.0.0
  very_good_analysis: ^7.0.0