name: app_logger
description: A reusable logging service for the host app.

publish_to: none

environment:
  sdk: ^3.0.6

dependencies:
  meta: ^1.12.0
  loghub:
    path: ../../../loghub

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.0
