include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

  errors:
    camel_case_types: error
    camel_case_extensions: error
    avoid_dynamic_calls: error
    prefer_single_quotes: error
    cancel_subscriptions: error
    provide_deprecation_message: error
    always_declare_return_types: error
    avoid_unused_constructor_parameters: error
    lines_longer_than_80_chars: warning

linter:
  rules:
    avoid_print: false
    document_ignores: false
    unnecessary_breaks: false
    one_member_abstracts: false
    sort_pub_dependencies: false
    public_member_api_docs: false
    unnecessary_raw_strings: false
    sort_constructors_first: false
    require_trailing_commas: false
    constant_identifier_names: false
    depend_on_referenced_packages: false
    avoid_catches_without_on_clauses: false
    prefer_constructors_over_static_methods: false
    always_put_required_named_parameters_first: false
    missing_whitespace_between_adjacent_strings: false
