name: analysis_plugin_test_helper
description: Dump of reusable utilities to help test analyzer plugins.

repository: https://github.com/Ragibn5/dart-flutter-packages
issue_tracker: https://github.com/Ragibn5/dart-flutter-packages/issues
homepage: https://github.com/Ragibn5/dart-flutter-packages/tree/main/analysis_plugin_test_helper

# Library version
version: 1.0.0

# Range of compatible SDK versions
environment:
  sdk: ^3.11.0

# Regular dependencies
# (Bundled in executable artifact)
dependencies:
  path: ^1.9.0
  analysis_server_plugin: ^0.3.0
  analyzer_plugin: ^0.13.0
  analyzer: ^8.0.0
  analyzer_testing: ^0.1.5

# Dev dependencies
# (NOT Bundled in executable artifact - For DEV use only)
dev_dependencies:
  test: ^1.25.6
  mocktail: ^1.0.4
  lints: ^6.0.0
  very_good_analysis: ^7.0.0

