name: clean_arch_lint
description: Analysis server plugin to enforce clean architecture.

repository: https://github.com/Ragibn5/dart-flutter-packages
issue_tracker: https://github.com/Ragibn5/dart-flutter-packages/issues
homepage: https://github.com/Ragibn5/dart-flutter-packages/tree/main/clean_arch_lint

# Library version
version: 1.0.0

# Range of compatible SDK versions
environment:
  sdk: ^3.11.0

# Regular dependencies
# (Bundled in executable artifact)
dependencies:
  path: ^1.9.0
  meta: ^1.12.0
  yaml: ^3.1.3
  string_extensions:
    path: ../string_extensions
  analysis_server_core:
    path: ../analysis_server_core

# Dev dependencies
# (NOT Bundled in executable artifact - For DEV use only)
dev_dependencies:
  test: ^1.25.6
  mocktail: ^1.0.4
  lints: ^6.0.0
  very_good_analysis: ^7.0.0
  analysis_plugin_test_helper: ^1.0.4
