name: json_converters
description: A collection of reusable JSON converter implementations for json_serializable based modules.

publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  datetime_utils:
    path: ../../../datetime_utils
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
