name: string_extensions
description: Useful extensions over dart's built-in `String` data type.

repository: https://github.com/Ragibn5/dart-flutter-packages
issue_tracker: https://github.com/Ragibn5/dart-flutter-packages/issues
homepage: https://github.com/Ragibn5/dart-flutter-packages/tree/main/string_extensions

# This prevents you from accidentally publish to pub.dev
publish_to: 'none'

# Library version
version: 0.0.1

# Range of compatible SDK versions
environment:
  sdk: ^3.0.6

dev_dependencies:
  # Test
  test: ^1.25.5

  # Lints
  lints: ^3.0.0
  very_good_analysis: ^5.1.0
