# ==========================================
# Configuration for `clean_arch_lint` plugin
# ==========================================

# Global Log Configuration: Controls logging for all rules.
log_config:
  # Enable or disable logging for all rules (default: false)
  enabled: true
  # Individual log levels (overrides `enabled`)
  # (Defaults - info: false, warning: true, error: true)
  allow_info: false
  allow_warning: true
  allow_error: true
  # Relative(to project root) path where logs will be saved
  # (Default: logs/analyzer_plugins/clean_arch_lint)
  log_dir_relative_path: logs/analyzer_plugins/clean_arch_lint

# Global Scan Configuration: Controls which project directories are scanned.
scan_config:
  # Scan the `lib/` directory (default: true)
  scan_lib_dir: true
  # Scan the `test/` directory (default: false)
  scan_test_dir: false

# Config for `clean_arch_dependency_direction` rule
clean_arch_dependency_direction:
  # Exclude Dart core packages from analysis (default: true)
  # e.g., dart:core, dart:async, etc.
  exclude_core_dart_packages: true
  # Name(s) of domain folder(s) in the project (default: ['domain'])
  domain_dir_names:
    - domain
    - application
  # Package-root-relative paths to exclude from analysis (default: [])
  # Example: To exclude `lib/core/*`, write `lib/core/`
  excluded_project_paths:
  # External library packages to exclude from analysis (default: [])
  # Specify package names as strings
  # Example: equatable, freezed, json_serializable
  excluded_library_packages:
    - equatable
    - disposable
    - net_models
    - dart_functionals