# Make sure to change file paths and others according to your project location & preferences.
json_parser:
  default_parser:
    class_name: DefaultJsonParser
    output_file: /Users/ragib/AndroidStudioProjects/dart-flutter-packages/app_template/lib/app/infrastructure/parser/default_json_parser.dart
  keyed_parsers:
    - APP_SERVER_MODELS_PARSER:
        class_name: AppServerModelsParser
        output_file: /Users/ragib/AndroidStudioProjects/dart-flutter-packages/app_template/lib/app/infrastructure/parser/app_server_models_parser.dart
    - APP_SERVER_TOKEN_REFRESH_MODELS_PARSER:
        class_name: AppServerTokenRefreshModelsParser
        output_file: /Users/ragib/AndroidStudioProjects/dart-flutter-packages/app_template/lib/app/infrastructure/parser/app_server_token_refresh_models_parser.dart
