name: crashlytics
description: A reusable crashlytics service.

publish_to: none

environment:
  sdk: ^3.10.9

dependencies:
  flutter:
    sdk: flutter
  firebase_crashlytics: ^4.3.5
  initializable:
    path: ../../../initializable

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
