name: base_auth_interceptor
description: Base auth interceptor to create specific implementations.

publish_to: none

environment:
  sdk: ^3.0.6

dependencies:
  net_kit:
    path: ../../../net_kit

dev_dependencies:
  test: ^1.25.5
  mocktail: ^1.0.5
