name: dlogger
description: A simple and extensible logging solution for dart and flutter apps with handy pre-built loggers.

repository: https://github.com/Ragibn5/dart-flutter-packages
issue_tracker: https://github.com/Ragibn5/dart-flutter-packages/issues
homepage: https://github.com/Ragibn5/dart-flutter-packages/tree/main/dlogger

# Library version
version: 1.0.0

# Range of compatible SDK versions
environment:
  sdk: ^3.0.6

# Regular dependencies
# (Bundled in executable artifact)
dependencies:
  path: ^1.8.0
  meta: ^1.12.0
  dart_functionals: ^1.0.0

# Dev dependencies
# (NOT Bundled in executable artifact - For DEV use only)
dev_dependencies:
  test: ^1.24.9
  mocktail: ^1.0.5
  lints: ^3.0.0
  very_good_analysis: ^5.1.0
