name: media_provider
description: "A package to access platform media contents"

repository: https://github.com/Ragibn5/dart-flutter-packages
issue_tracker: https://github.com/Ragibn5/dart-flutter-packages/issues
homepage: https://github.com/Ragibn5/dart-flutter-packages/tree/main/media_provider/media_provider

# Library version
version: 1.0.0

# Range of compatible SDK versions
environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

# Regular dependencies
# (Bundled in executable artifact)
dependencies:
  meta: ^1.12.0
  flutter:
    sdk: flutter
  media_provider_platform_interface:
    path: ../media_provider_platform_interface
  media_provider_android:
    path: ../media_provider_android

# Dev dependencies
# (NOT Bundled in executable artifact - For DEV use only)
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  lints: ^3.0.0
  very_good_analysis: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        default_package: media_provider_android