name: preference_store
description: Key-value data store.

publish_to: none

environment:
  sdk: ^3.0.6

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  shared_preferences_platform_interface: ^2.4.2
